version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::694963961769:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-1UFFN9XYF1K9F"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::694963961769:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-1SG9FFN5TU2W0"
cloudformation_execution_role = "arn:aws:iam::694963961769:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-1PDRR7L9DVWWX"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-lciga28py275"
image_repository = ""
region = "us-west-2"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::694963961769:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-13UHXT27IUO95"
cloudformation_execution_role = "arn:aws:iam::694963961769:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-RIEX9OB8RA0U"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-sw19q5vfn6ut"
image_repository = ""
region = "us-east-1"
